tautulli_server_url = "http://server1-stats.omniplex.club/"
tautulli_server_cookie = "tautulli_token_608ecf9fab56436b96d62243b0a05470=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTIxOTUyMCwidXNlciI6IlByb2JhYmx5QUhhY2hlciIsInVzZXJfZ3JvdXAiOiJndWVzdCIsImV4cCI6MTY5OTc0MTE5OH0.dxRpnqegZkgCr57k068-Km5CcTOxM9A-JQ9QF4zfZW0"
discord_username = "probablyAHacher"
metadata_sources = ["native_now_playing"]

[tautulli]
tautulli_server_url = "http://server1-stats.omniplex.club/"
tautulli_server_cookie = "tautulli_token_608ecf9fab56436b96d62243b0a05470=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTIxOTUyMCwidXNlciI6IlByb2JhYmx5QUhhY2hlciIsInVzZXJfZ3JvdXAiOiJndWVzdCIsImV4cCI6MTY5OTc0MTE5OH0.dxRpnqegZkgCr57k068-Km5CcTOxM9A-JQ9QF4zfZW0"
