discord_username = "gamer"
parsers = ["extension", "tautulli", "native_now_playing"]

[tautulli]
tautulli_server_url = "http://server1.example.com"
tautulli_server_cookie = "" # enter your cookie here after logging into tautulli

