[package]
name = "drp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["macros", "json"] }
config = { version = "0.15.25", features = ["toml"] }
discord-rich-presence = "1.1.0"
futures = "0.3.34"
lazy_static = "1.5.0"
reqwest = { version = "0.13.4", features = ["blocking", "cookies", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde-aux = "4.7.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal"] }
urlencoding = "2.1.3"
fltk = { version = "1.5.23", features = ["fltk-bundled"] }
toml = "1.1.4"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
dotenvy = "0.15.7"
tracing = "0.1.44"
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["trace"] }
dotenvy_macro = "0.15.7"
tray-icon = "0.24.2"
image = "0.25.10"
tokio-util = { version = "0.7.19", features = ["rt"] }

[target.'cfg(target_os = "linux")'.dependencies]
mpris = "2.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = ["Media_Control", "Foundation", "Foundation_Collections", "Storage_Streams", "Win32_Foundation"] }

# cacao = "0.3.2"

[profile.release]
strip = "symbols"
opt-level="z"

[lints.clippy]
panic = "warn"
unwrap_used = "warn"
expect_used = "warn"

[build-dependencies]
dotenvy = "0.15.7"
